### ISSUE TITLE
Response code 204

### ISSUE THREAD

**Issue by mrkale** [InitialState/public-api-docs#1]
In contrast to description of the successful request "https://api.initialstate.com/api/v1/buckets" I got the response code **201** instead of declared code **204** as depicted in the following picture:

![image](https://cloud.githubusercontent.com/assets/5478719/5327837/9e51cdc6-7d63-11e4-9159-53c633bd3b77.png)

**Comment by davidsulpy** [comment]
Thanks for reporting this! I'll updated the documentation. There is new documentation for a brand new release version of the api that will be launched very soon, this has a much simpler interface. You can check out the documentation in apiary [here](http://docs.initialstateeventsapi.apiary.io/). As soon as the design is finalized the api will be released!

**Comment by davidsulpy** [comment]
Fixed in https://github.com/InitialState/log-api-docs/commit/2569510170c0ee1a1c66e2076f4afe1b00aae5f0
