### ISSUE TITLE
Duplicate buckets

### ISSUE THREAD

**Issue by mrkale** [InitialState/public-api-docs#2]
Multiple requests "https://api.initialstate.com/api/v1/buckets" with the same body are all successful and they create multiple buckets. Then a request "https://groker.initialstate.com/batch_logs" logs a value to all of those multiple buckets. It would be great to implement some checking for multiplicity so that subsequent requests with the duplicate bucket name or bucket id would be rejected with particular error response code.

**Comment by davidsulpy** [comment]
Thanks for reporting this! Our new api will be available with the next few days and will address this and many other usability issues. You can see the documentation of the future api [here](http://docs.initialstateeventsapi.apiary.io/) to be released soon!
